config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'welcome#index'

  resources :collaborations
  resources :posts
  resources :comments
  resources :contents
  resources :assets
  resources :memberships

  get '/collaborations/:id/new-post' => 'posts#new'
  get '/collaborations/:collaboration_id/posts/:id' => 'posts#show'

  namespace :api, defaults: {format: :json} do
    get '/platforms' => 'platforms#index'
  end

end

app/models/action.rb
class Action < FeedItem
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :post
  has_one :image, as: :imageable, dependent: :destroy
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  has_many :posts
  has_many :memberships
  has_many :users, through: :memberships
  has_many :campaigns
end

app/models/comment.rb
class Comment < FeedItem
end

app/models/feed_item.rb
class FeedItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true

  # Paperclip
  has_attached_file :attachment
  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\Z/

  def url
    attachment.url
  end

  def as_json(options={})
    super(methods: :url)
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :collaboration
end

app/models/photo.rb
class Photo < Asset
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :collaboration
  belongs_to :user
  belongs_to :platform
  has_many :feed_items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :assets, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings

  enum status: [ :draft, :pending, :approved ]

  accepts_nested_attributes_for :feed_items
  accepts_nested_attributes_for :assets

  scope :during, ->(time_frame) {
    where scheduled_at: time_frame
  }

  attr_accessor :time_zone
  before_save :use_selected_time_zone

  def use_selected_time_zone
    return unless self.time_zone
    time_zone = ActiveSupport::TimeZone.new self.time_zone
    self.scheduled_at -= time_zone.utc_offset
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable

  has_many :memberships
  has_many :collaborations, through: :memberships
  has_many :campaigns, through: :collaborations
  has_many :posts
  has_many :comments

  has_one :avatar, as: :imageable, dependent: :destroy
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def index
    @post = Post.find_by_id(params[:post_id])
    @assets = @post.assets
    render json: @assets.to_json(include: {image: {methods: :url}})
  end

  def create
    @post = Post.find_by_id(params[:asset][:post_id])
    @asset = @post.assets.new(asset_params)
    attachment = params[:asset][:image][:attachment]
    image = Image.new
    image.attachment = attachment.tempfile
    @asset.image = image
    if @asset.save
      render json: @asset.to_json(include: {image: {methods: :url}})
    else
      render json: nil, status: 400
    end
  end

  def update
    @asset = Asset.find(params[:id])
    @asset.update(asset_params)
    if @asset.save
      render json: @asset.to_json(include: {image: {methods: :url}})
    else
      render json: nil, status: 400
    end
  end

  def asset_params
    params.require(:asset).permit(:id, :approved_at)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    # @collaboration = Collaboration.find_by_id(params[:collaboration_id])
    # @post = Post.new
    # @comment = @post.comments.build
    # @content = @post.contents.build
  end

  def index
    @collaboration = Collaboration.find_by_id(params[:collaboration_id])

    start_date = params[:start].to_datetime
    end_date = params[:end].to_datetime

    @posts = @collaboration.posts.during(start_date..end_date)

    render json: @posts
  end

  def create
    # @collaboration = Collaboration.find_by_id(params[:collaboration_id])
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    scheduled_at = DateTime.parse(params[:scheduled_at]).change(offset: (-params[:timezone_offset].to_f/(24*60*60)))
    @post.scheduled_at = scheduled_at
    @post.save
    render json: @post
  end

  def edit
  end

  def update
  end

  def show
    @post = Post.includes(assets: {assets: :image}, feed_items: :user).find_by_id(params[:id])
    if @post && request.xhr?
      render json: @post.to_json(include: {
        assets: {include: {assets: {include: {image: {methods: :url}}}}},
        feed_items: {include: :user}
      })
    end
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :collaboration_id, :platform_id, :copy, :title, :description, :scheduled_at, :time_zone,
      :comments_attributes => [:id, :body, :user_id, :post_id],
      :assets_attributes => [:id, :post_id, :image])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/campaigns/new.html.erb
<h2>Create Campaign</h2>

<%= form_for @campaign, url: collaboration_campaigns_url do |f| %>

  <div><%= f.label :name %><br />
  <%= f.text_field :name, autofocus: true %></div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description, autofocus: true %>
  </div>

  <div><%= f.submit "Create Campaign" %></div>

<% end %>

app/views/campaigns/show.html.erb
<h2><%= @campaign.name %></h2>

<p>
  <%= @campaign.description %>
</p>

<p>
  <%= link_to "Create Post", new_campaign_post_url(@campaign) %>
</p>

<div class='row'>
  <div class='small-1 columns'>
    <a id='left-arrow'><i class='fi-arrow-left'></i></a>
  </div>
  <div class='small-1 columns'>
    <a id='right-arrow'><i class='fi-arrow-right'></i></a>
  </div>
</div>

<div class='row'>
  <div class='small-12 columns'>
    <ul id='calendar' data-campaign-id="<%=@campaign.id%>" class="small-block-grid-7">
    </ul>
  </div>
</div>

<p>
  <%= link_to "Back", collaboration_url(@campaign.collaboration) %>
</p>

<script type="text/template" id="day-template">
  <li class='day-list-item'>
    <div class='day-title'>
      <%%= moment.day %> <%%= moment.month %>/<%%= moment.date %>
    </div>
    <ul class='post-list'>
    <%% _.each(posts, function(p) { %>
      <li class='post-list-item'>
        <div class='post-title'>
          <a href="/posts/<%%= p.id%>"><%%= p.name %> <%%= p.time %></a>
        </div>
      </li>
    <%% }) %>
    </ul>
  </li>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Scribbly" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">Scribbly</a></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <% if current_user %>
            <li><%= link_to "Sign Out", destroy_user_session_url, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_url %></li>
            <li><%= link_to "Sign Up", new_user_registration_url %></li>
          <% end %>
        </ul>

      </section>
    </nav>
    <div id="content" class="small-12 columns">
      <% if current_user %>
        <%= react_router 'routes', 'HistoryLocation' %>
      <% else %>
        <%= yield %>
      <% end %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>